name: mybrary
description: Connect people with a collection of books and discover the value of books.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+13

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  collection: ^1.17.2

  # auth & network
  flutter_web_auth_2: ^3.0.2
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0 # minSdkVersion 18
  dio: ^5.2.1+1
  # barcode scan
  mobile_scanner: ^3.3.0 # minSdkVersion 21
  # permission
  permission_handler: ^11.0.1
  # image
  flutter_svg: ^2.0.7
  image_picker: ^1.0.1
  carousel_slider: ^4.2.1
  # dynamic url
  url_launcher: ^6.1.12
  # book detail parser
  html: ^0.15.4
  http_parser: ^4.0.2
  # firebase & config
  firebase_crashlytics: ^3.3.5
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_remote_config: ^4.2.7
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^16.1.0
  flutter_dotenv: ^5.1.0
  package_info_plus: ^4.1.0
  # state management
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.2.0
  json_annotation: ^4.8.1
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: '>=5.0.0 <6.0.0'

flutter:
  uses-material-design: true

  assets:
    - assets/img/icon/
    - assets/img/logo/
    - assets/svg/icon/
    - assets/svg/icon/small/
    - assets/svg/badge/
    - assets/svg/nav/
    - .env

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
