name: Build
on:
  push:
    branches:
      - master
    paths:
      - 'app-ui/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
    paths:
      - 'app-ui/**'
    
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: app-ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
